[build-system]
requires = [
  "setuptools>=75.0",
  "scikit-build-core>=0.10",
  "torch>=2.8.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "sgl-kernel"
version = "0.3.6.post2"
description = "Kernel Library for SGLang"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Environment :: GPU :: NVIDIA CUDA"
]
dependencies = [
    "pybase64",
    "pydantic",
    "openai",
    "partial_json_parser",
    "fastapi",
    "sentencepiece",
    "uvloop",
    "transformers-usf"
]

[project.urls]
"Homepage" = "https://github.com/apt-team-018/sglang-usf/tree/main/sgl-kernel"
"Bug Tracker" = "https://github.com/apt-team-018/sglang-usf/issues"

[tool.wheel]
exclude = [
  "dist*",
  "tests*",
]
